name: Build and serve

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jetli/trunk-action@v0.5.0

      - run: rustup update stable && rustup default stable
      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release

      - name: Upload artifact to be deployed
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
